#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
ln -sf $OPENSHIFT_DATA_DIR/info.json $OPENSHIFT_REPO_DIR/wsgi/static/info.json
if [ -e $OPENSHIFT_REPO_DIR/wsgi/.cp_passwd ]
then
    cp $OPENSHIFT_REPO_DIR/wsgi/.cp_passwd $OPENSHIFT_DATA_DIR/.cp_passwd
fi

if [ -e $OPENSHIFT_REPO_DIR/wsgi/.pb_key ]
then
    cp $OPENSHIFT_REPO_DIR/wsgi/.pb_key $OPENSHIFT_DATA_DIR/.pb_key
fi
